name: Test FHE Game Demo

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        sudo apt-get install -y libomp-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install concrete-python --index-url https://pypi.zama.ai/simple
    - name: Run demo test
      run: python fhe_game_demo.py single  # Simulated run
    - name: Lint code
      run: pip install flake8; flake8 fhe_game_demo.py
